server:
  port: 8080
#  servlet:
#    context-path: /learn 

domain:
  internal:
    database:
      reader: localhost:5433
      writer: localhost:5433
spring:
  application:
    name: LearnJava
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
database:
  writer:
    url: jdbc:postgresql://${domain.internal.database.writer}/LearnJava?&connectTimeout=10&socketTimeout=10&tcpKeepAlive=true
    username: postgres
    password: 123456
  reader:
    url: jdbc:postgresql://${domain.internal.database.reader}/LearnJava?&connectTimeout=10&socketTimeout=10&tcpKeepAlive=true
    username: postgres
    password: 123456

jwt:
  privateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDN2l3QFltdHa3Z
    kv6hlgdjxh2VUuF1LhCvfJFppy+zHXQAeGWyBwHw2clCYdNlwMCy/Bp/rQgYlC5T
    B5mvZ/73SdfPtvySz8MaaL5bKlgZjT70j8TDx6FwOri1SJHBNWksKCvfQ1gZu+4W
    zvSCPRyVt+EagN7mxkN8E6GRgmEQBc88MpGSlFxEmgA4mbM6rgGXx5rUV3p9f9WH
    xr4fXAYRC+b/Srgf60q0xCic+nt5BmmH/RgQ2UKRAGEzq1Qm6HopydpuEVB63vPt
    /NgNGlnz3tlNT6x8I72gVVOIAcP+U1owA2rASlOWJVKxaURR6uiIGFnst1ZweckK
    3ADC315DAgMBAAECggEAHFAqkxJgIqCQZtqW9zahcZGwQ/eQVwOs+9YQUg3Su7oT
    WHU215OrKqtpyR2Xa+llF7khE+qCsI7BCF6FPuD46p5XdpRejPrShPFfLT7Xuzv4
    Kr8TezIb/Em3WgfPNFnaS16DGkQy++cjSjPQ4ZDyO419Ap4zCl6+rXQtxsu9+evz
    R7WrxQDBNxtfYWd/hpWh4FWFNRCRZIlCoIfywP+FmdGkOEgZhR8T0sKmIy5UUxqu
    PIAr61EsZiOScqHFXhk0iK+tOJhqzDOgWzpiXs2U8aNo8bjTrrVG4fD6YBIwqcrc
    m5HOi99MsEhVLOgxGHetSw6qW4nJNLoKXZgZ31QS4QKBgQD48kD4EgE+QbIKaJo3
    3JWzIzFliHhpVG6F2quQpOoH3okQmmg2Iur2n90gPSJX+X4M8vZ+3quRipsLi7mX
    kSKBChzzV2X68CInM/+0SbEG20bU2PL9wD1mUraDkS7Wa1uOf0IjMaI+AMFxlj7b
    QzUMHeCSNo+mX5TND3pRUVpI6wKBgQDTr4hreYQ6sxWruPgDvkg7p8f6fb+ksmSM
    O0L1VR6Xv3RotuVL77Fn2lPk0nRaquZUFdZ5+GGdgVAhnvatpnTYEaPCq/OLfCCy
    LSjGH1DoVU20rKhqIdRYzV5kPZTS/e/VDN+qHYOow/6QBDx5DnYUrvKdGvjOYgbr
    hSqanSTqCQKBgQCjw3lJt05qDf15K2aH6Ovxc+1CxYuwfoJWO4sxE8uAcbvo2CpF
    sqKuqmtkkdLN3Ko3Cn1s6D4k9/EWn0vvkOIJ0QVKbuv/L4jIEUTc7L0vrX/i9PSk
    SJobfb3ivtb45pbMHpr7W+NGtmiKuDOROZzj46Ofi5Tj9WyFmPD2HXYvEQKBgQCW
    l9amFsGh/Msa6jDOgOzkO51Br3nJ0ftD49jjrVVhQRuwbwS6u99qcWCjdbC+27uV
    8B8vkCrpoRf/gxYcPUH8gLgOgsN05K5h80yBfb/SOPVZ5ka9kil9r0RKbaDVZT/c
    QhdP70U9p4kOrWTT/hy05CzG5WxBbm1b2dWQPuEG+QKBgCGplOaS6yASf7pxoqJS
    dHMiE+zwPRiboP8HhgvpOieHXt5dDqTkXUJrg7kmxv4GLGDBk3Dm77KF1JdhYOdn
    XtycuC6CrU+9wm7SjO9V4h4q6VgEaqhL27ylcP/JQsM2VaQZUvomSIWXmqV07cri
    668NrqXlRh89eewck3KtiQFV
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzdpd0BZbXR2t2ZL+oZYH
    Y8YdlVLhdS4Qr3yRaacvsx10AHhlsgcB8NnJQmHTZcDAsvwaf60IGJQuUweZr2f+
    90nXz7b8ks/DGmi+WypYGY0+9I/Ew8ehcDq4tUiRwTVpLCgr30NYGbvuFs70gj0c
    lbfhGoDe5sZDfBOhkYJhEAXPPDKRkpRcRJoAOJmzOq4Bl8ea1Fd6fX/Vh8a+H1wG
    EQvm/0q4H+tKtMQonPp7eQZph/0YENlCkQBhM6tUJuh6KcnabhFQet7z7fzYDRpZ
    897ZTU+sfCO9oFVTiAHD/lNaMANqwEpTliVSsWlEUeroiBhZ7LdWcHnJCtwAwt9e
    QwIDAQAB
    -----END PUBLIC KEY-----
  jwtRefreshExpirationS: 60
  jwtAccessTokenExpirationS: 30
  issuer: LearnJava
